# Generated by Django 2.2.3 on 2019-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='curses/image', verbose_name='Imagem'),
        ),
    ]
